CLASS zcl_fg100_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC FOR EVENTS OF ZFG100_R_Travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_fg100_handler IMPLEMENTATION.
ENDCLASS.
